In [1]:
##import numpy 
import numpy as np ##numpy developed in 2005 by Travis Oliphant

In [2]:
np.__version__

'1.23.5'

In [3]:
print(np.__doc__)


NumPy
=====

Provides
  1. An array object of arbitrary homogeneous items
  2. Fast mathematical operations over arrays
  3. Linear Algebra, Fourier Transforms, Random Number Generation

How to use the documentation
----------------------------
Documentation is available in two forms: docstrings provided
with the code, and a loose standing reference guide, available from
`the NumPy homepage <https://numpy.org>`_.

We recommend exploring the docstrings using
`IPython <https://ipython.org>`_, an advanced Python shell with
TAB-completion and introspection capabilities.  See below for further
instructions.

The docstring examples assume that `numpy` has been imported as `np`::

  >>> import numpy as np

Code snippets are indicated by three greater-than signs::

  >>> x = 42
  >>> x = x + 1

Use the built-in ``help`` function to view a function's docstring::

  >>> help(np.sort)
  ... # doctest: +SKIP

For some objects, ``np.info(obj)`` may provide additional help.  This is
particularly tr

In [4]:
##why numpy
##mathematical functions 
##faster as compare to list and it is fast because it is developed in c++ which use array and c++ is upgarded version of c and c++ is fater language in present scenario


In [5]:
# list convert into numpy array
l = [1,2,3,4,5,6]
arr = np.array(l)

In [6]:
type(arr) ##ndarray is n dimentinal array 
# why array - array is the way numpy stores the data
# array is only stores homogineous(Similar) type of data


numpy.ndarray

In [7]:
##find dimmension
##Convert a number or string to an integer, or return 0 if no arguments
# are given.  If x is a number, return x.__int__().  For floating point
# numbers, this truncates towards zero.

# If x is not a number or if base is given, then x must be a string,
# bytes, or bytearray instance representing an integer literal in the
# given base.  The literal can be preceded by '+' or '-' and be surrounded
# by whitespace.  The base defaults to 10.  Valid bases are 0 and 2-36.
# Base 0 means to interpret the base from the string as an integer literal.
# >>> int('0b100', base=0)
arr.ndim ##simpy it gives dimmension of the given data

1

In [8]:
l = [1,2,3,4,5,'rishi']
arr1 = np.array(l)
arr1 #array(['1', '2', '3', '4', '5', 'rishi'], dtype='<U21') here all the elements convert into string because one element is string

array(['1', '2', '3', '4', '5', 'rishi'], dtype='<U21')

In [9]:
arr1.ndim

1

In [10]:
arr2 = np.array([[1,2,3],[4,5,6]])

In [11]:
arr2.ndim #here dimmension is 2 

2

In [12]:
# Matrix
l2 = [1,2,3,4]
mat = np.matrix(l2) ##Matrix will be bydefault 2d
# Init signature: np.matrix(data, dtype=None, copy=True)
# Docstring:     
# matrix(data, dtype=None, copy=True)

# .. note:: It is no longer recommended to use this class, even for linear
#           algebra. Instead use regular arrays. The class may be removed
#           in the future.

# Returns a matrix from an array-like object, or from a string of data.
# A matrix is a specialized 2-D array that retains its 2-D nature
# through operations.  It has certain special operators, such as ``*``
# (matrix multiplication) and ``**`` (matrix power).

# Parameters
# ----------
# data : array_like or string
#    If `data` is a string, it is interpreted as a matrix with commas
#    or spaces separating columns, and semicolons separating rows.
# dtype : data-type
#    Data-type of the output matrix.
# copy : bool
#    If `data` is already an `ndarray`, then this flag determines
#    whether the data is copied (the default), or whether a view is
#    constructed.

# See Also
# --------
# array

# Examples
# --------
# >>> a = np.matrix('1 2; 3 4')
# >>> a
# matrix([[1, 2],
#         [3, 4]])

# >>> np.matrix([[1, 2], [3, 4]])
# matrix([[1, 2],
#         [3, 4]])
# File:           /opt/conda/lib/python3.10/site-packages/numpy/__init__.py
# Type:           type
# Subclasses:  

In [13]:
mat = np.matrix([[[1,2],[3,4],[5,6]]]) #ValueError: matrix must be 2-dimensional 
#matrix is the subclass of array

ValueError: matrix must be 2-dimensional

In [14]:
np.array([[[1,2],[3,4],[5,6]]])

array([[[1, 2],
        [3, 4],
        [5, 6]]])

In [15]:
np.asarray([[[1,2],[3,4],[5,6]]])

array([[[1, 2],
        [3, 4],
        [5, 6]]])

In [16]:
np.asanyarray([[[1,2],[3,4],[5,6]]])

array([[[1, 2],
        [3, 4],
        [5, 6]]])

In [17]:
np.asanyarray(mat) #Convert the input to an ndarray, but pass ndarray subclasses through.

matrix([[1, 2, 3, 4]])

In [18]:
##tuple into array
t = (1,2,3,4)
arr = np.array(t)
arr

array([1, 2, 3, 4])

In [19]:
##shallow 
arr = np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [20]:
a = arr
a

array([1, 2, 3, 4, 5])

In [21]:
arr[0] = 1000
arr

array([1000,    2,    3,    4,    5])

In [22]:
a

array([1000,    2,    3,    4,    5])

In [23]:
# deep copy
arr = [2,3,4,5]
b = arr.copy()
print("a :",arr)
print("b :",b)

a : [2, 3, 4, 5]
b : [2, 3, 4, 5]


In [24]:
arr[0] = 1000
print("a :",arr)
print("b :",b)

a : [1000, 3, 4, 5]
b : [2, 3, 4, 5]


In [25]:
#to create array >> .array,.asarray,.asanyarray,
# deep copy and shallow copy

In [26]:
#there are multiple ways to generating arrays
np.fromfunction(lambda i,j: i==j,shape= (3,3)) ##Construct an array by executing a function over each coordinate.

# The resulting array therefore has a value ``fn(x, y, z)`` at
# coordinate ``(x, y, z)``.

# Parameters
# ----------
# function : callable
#     The function is called with N parameters, where N is the rank of
#     `shape`.  Each parameter represents the coordinates of the array
#     varying along a specific axis.  For example, if `shape`
#     were ``(2, 2)``, then the parameters would be
#     ``array([[0, 0], [1, 1]])`` and ``array([[0, 1], [0, 1]])``
# shape : (N,) tuple of ints
#     Shape of the output array, which also determines the shape of
#     the coordinate arrays passed to `function`.
# dtype : data-type, optional
#     Data-type of the coordinate arrays passed to `function`.
#     By default, `dtype` is float.
# like : array_like, optional
#     Reference object to allow the creation of arrays which are not
#     NumPy arrays. If an array-like passed in as ``like`` supports
#     the ``__array_function__`` protocol, the result will be defined
#     by it. In this case, it ensures the creation of an array object
#     compatible with that passed in via this argument.

#     .. versionadded:: 1.20.0

# Returns
# -------
# fromfunction : any
#     The result of the call to `function` is passed back directly.
#     Therefore the shape of `fromfunction` is completely determined by
#     `function`.  If `function` returns a scalar value, the shape of
#     `fromfunction` would not match the `shape` parameter.

# See Also
# --------
# indices, meshgrid

# Notes
# -----
# Keywords other than `dtype` are passed to `function`.

# Examples
# --------
# >>> np.fromfunction(lambda i, j: i, (2, 2), dtype=float)
# array([[0., 0.],
#        [1., 1.]])
       
# >>> np.fromfunction(lambda i, j: j, (2, 2), dtype=float)    
# array([[0., 1.],
#        [0., 1.]])
       
# >>> np.fromfunction(lambda i, j: i == j, (3, 3), dtype=int)
# array([[ True, False, False],
#        [False,  True, False],
#        [False, False,  True]])

# >>> np.fromfunction(lambda i, j: i + j, (3, 3), dtype=int)
# array([[0, 1, 2],
#        [1, 2, 3],
#        [2, 3, 4]])
# File:      /opt/conda/lib/python3.10/site-packages/numpy/core/numeric.py
# Type:      function

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [27]:
np.fromfunction(lambda i,j: i*j,shape= (3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [28]:
range(2)

range(0, 2)

In [29]:
iterater = (i*i for i in range(5))

In [30]:
# create np array using iterater
np.fromiter(iterater,int)

array([ 0,  1,  4,  9, 16])

In [31]:
##Generate array from string
np.fromstring('23 4 5 6',sep = ' ',dtype = int)

array([23,  4,  5,  6])

In [32]:
lit = [1,2,3,4,5,6]
arr = np.array(lit)

In [33]:
arr

array([1, 2, 3, 4, 5, 6])

In [34]:
arr.size

6

In [35]:
arr.shape

(6,)

In [36]:
arr.dtype

dtype('int64')

In [37]:
list(range(3))

[0, 1, 2]

In [38]:
list(range(1.5,10.6)) ##range can not deal with float value

TypeError: 'float' object cannot be interpreted as an integer

In [39]:
np.arange(0.1,10.5,0.2)

array([ 0.1,  0.3,  0.5,  0.7,  0.9,  1.1,  1.3,  1.5,  1.7,  1.9,  2.1,
        2.3,  2.5,  2.7,  2.9,  3.1,  3.3,  3.5,  3.7,  3.9,  4.1,  4.3,
        4.5,  4.7,  4.9,  5.1,  5.3,  5.5,  5.7,  5.9,  6.1,  6.3,  6.5,
        6.7,  6.9,  7.1,  7.3,  7.5,  7.7,  7.9,  8.1,  8.3,  8.5,  8.7,
        8.9,  9.1,  9.3,  9.5,  9.7,  9.9, 10.1, 10.3])

In [40]:
list(np.arange(0.1,10.5,0.2))

[0.1,
 0.30000000000000004,
 0.5000000000000001,
 0.7000000000000001,
 0.9000000000000001,
 1.1000000000000003,
 1.3000000000000003,
 1.5000000000000004,
 1.7000000000000004,
 1.9000000000000004,
 2.1000000000000005,
 2.3000000000000007,
 2.5000000000000004,
 2.7000000000000006,
 2.900000000000001,
 3.1000000000000005,
 3.3000000000000007,
 3.500000000000001,
 3.7000000000000006,
 3.900000000000001,
 4.1000000000000005,
 4.300000000000001,
 4.500000000000001,
 4.7,
 4.9,
 5.1000000000000005,
 5.300000000000001,
 5.500000000000001,
 5.700000000000001,
 5.9,
 6.1000000000000005,
 6.300000000000001,
 6.500000000000001,
 6.700000000000001,
 6.900000000000001,
 7.100000000000001,
 7.300000000000001,
 7.500000000000001,
 7.700000000000001,
 7.900000000000001,
 8.100000000000001,
 8.3,
 8.500000000000002,
 8.700000000000001,
 8.900000000000002,
 9.100000000000001,
 9.3,
 9.500000000000002,
 9.700000000000001,
 9.900000000000002,
 10.100000000000001,
 10.300000000000002]

In [41]:
np.linspace(1,5,45)

array([1.        , 1.09090909, 1.18181818, 1.27272727, 1.36363636,
       1.45454545, 1.54545455, 1.63636364, 1.72727273, 1.81818182,
       1.90909091, 2.        , 2.09090909, 2.18181818, 2.27272727,
       2.36363636, 2.45454545, 2.54545455, 2.63636364, 2.72727273,
       2.81818182, 2.90909091, 3.        , 3.09090909, 3.18181818,
       3.27272727, 3.36363636, 3.45454545, 3.54545455, 3.63636364,
       3.72727273, 3.81818182, 3.90909091, 4.        , 4.09090909,
       4.18181818, 4.27272727, 4.36363636, 4.45454545, 4.54545455,
       4.63636364, 4.72727273, 4.81818182, 4.90909091, 5.        ])

In [42]:
np.logspace(start=2,stop=5,base= 2,num=20)

array([ 4.        ,  4.46263167,  4.97877036,  5.55460457,  6.19703857,
        6.91377515,  7.71340798,  8.60552469,  9.60082176, 10.71123281,
       11.95007169, 13.3321921 , 14.87416568, 16.59448071, 18.5137638 ,
       20.65502717, 23.0439446 , 25.70915925, 28.68262708, 32.        ])

In [43]:
arr1 = np.zeros(5)

In [44]:
arr2 = np.zeros((3,4),int)
arr2.shape

(3, 4)

In [45]:
arr2

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [46]:
arr3 = np.zeros((3,3,4),int)
arr3.shape

(3, 3, 4)

In [47]:
arr3

array([[[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]]])

In [48]:
arr3.ndim

3

In [49]:
arr = np.ones((3,2,3),int)

In [50]:
arr

array([[[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]]])

In [51]:
arr+5

array([[[6, 6, 6],
        [6, 6, 6]],

       [[6, 6, 6],
        [6, 6, 6]],

       [[6, 6, 6],
        [6, 6, 6]]])

In [52]:
arr = np.ones((3,4),int)

In [53]:
arr

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [54]:
arr+1

array([[2, 2, 2, 2],
       [2, 2, 2, 2],
       [2, 2, 2, 2]])

In [55]:
arr*5

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

In [56]:
np.empty((3,4),int) ##it gives some random value of shape is which you pass in this function

array([[     94420658525522,                   0,                   0,
                          0],
       [       240518168576, 4122824891620680804, 7219614595506649185,
        3761684590288646706],
       [4050482300833850672, 7234532945332429363, 3474021544973854307,
        3703429170025673061]])

In [57]:
np.eye(4,dtype=int) ##it is actually gives a digonal square matrix
##Provides
  # 1. An array object of arbitrary homogeneous items
  # 2. Fast mathematical operations over arrays
  # 3. Linear Algebra, Fourier Transforms, Random Number Generation

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [58]:
##out of the syllabus topic
import pandas as pd
df = pd.DataFrame(arr)
df

0  1  2  3
0  1  1  1  1
1  1  1  1  1
2  1  1  1  1

In [59]:
##xtra Topic
import random

In [60]:
random.choice("rahul")

'h'

In [61]:
random.randrange(1,10000)

852

In [62]:
random.random() ##random no. is generated between (0 and 1) where 0 will be included and 1 will be excluded

0.9155018294973409

In [63]:
ls = [1,2,3,4,5,6]
random.shuffle(ls)
ls

[4, 1, 5, 3, 2, 6]

In [64]:
random.uniform(7,14) ##a no. between 7 and 14 which have equal probability

12.397799129761548

##this same thing we can do using numpy library

In [65]:
np.random.rand(2)

array([0.61763022, 0.08144599])

In [66]:
np.random.rand(2,4)

array([[0.06888959, 0.43476797, 0.20453569, 0.67583063],
       [0.79199951, 0.98840671, 0.31646868, 0.59240694]])

In [67]:
np.random.randn(2,3) ##it is used  for create a graph for normal distribution or bell shaped curved

array([[ 1.95713177,  0.32207383,  0.00407542],
       [-0.10440129, -0.30958972, -0.36816499]])

In [68]:
np.random.random_sample()

0.01942773659803365

In [69]:
# [0,1) it is half bracket in which 0 will be included and 1 will be xcluded

In [70]:
np.random.randint(1,76,size = (3,4))

array([[ 7,  9, 57, 38],
       [34, 70, 23, 36],
       [67, 34, 37, 38]])

In [71]:
arr = np.random.randint(1,76,size = (3,4))

In [72]:
arr

array([[54, 27, 48, 68],
       [67, 63, 59, 72],
       [57, 61, 58, 63]])

In [73]:
arr.size

12

In [74]:
arr.shape

(3, 4)

In [75]:
arr.ndim

2

In [76]:
arr.reshape((4,3))

array([[54, 27, 48],
       [68, 67, 63],
       [59, 72, 57],
       [61, 58, 63]])

In [77]:
arr.reshape(4,-1) ##when we want 4 rows but we dont know how many columns we want so we -1 in this situation and numpy take of this situation

array([[54, 27, 48],
       [68, 67, 63],
       [59, 72, 57],
       [61, 58, 63]])

In [78]:
arr.reshape(4,-100000) # Note:- when we pass any neagative value numpy assume -1 and no changes occure in the result

array([[54, 27, 48],
       [68, 67, 63],
       [59, 72, 57],
       [61, 58, 63]])

In [79]:
arr.reshape(-1,3)##when we want 4 cols but we dont know how many rows we want so we -1 in this situation and numpy take of this situation

array([[54, 27, 48],
       [68, 67, 63],
       [59, 72, 57],
       [61, 58, 63]])

In [80]:
# arr.reshape(-1,-1) #ValueError: can only specify one unknown dimension

In [84]:
arr.reshape(12,1).base #this .base give the original function 

array([[54, 27, 48, 68],
       [67, 63, 59, 72],
       [57, 61, 58, 63]])

In [83]:
arr.reshape(2,2,3).base #this .base give the original function 

array([[54, 27, 48, 68],
       [67, 63, 59, 72],
       [57, 61, 58, 63]])

In [85]:
arr.reshape(2,2,3)

array([[[54, 27, 48],
        [68, 67, 63]],

       [[59, 72, 57],
        [61, 58, 63]]])

In [86]:
##create multiple dimmention
arr.reshape(1,1,1,1,1,1,2,2,3)

array([[[[[[[[[54, 27, 48],
              [68, 67, 63]],

             [[59, 72, 57],
              [61, 58, 63]]]]]]]]])

In [93]:
arr2 = np.zeros((1,3,4),int) ##3 rows ,2 colms with 2d + 1d extra dimention
arr2

array([[[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]]])

In [16]:
arr1 = np.random.randint(1,10,(5,6))
arr1

array([[3, 3, 7, 5, 3, 3],
       [5, 9, 5, 8, 3, 6],
       [5, 4, 6, 8, 9, 3],
       [4, 2, 6, 8, 8, 4],
       [9, 5, 3, 8, 9, 4]])

In [17]:
arr1 > 5 

array([[False, False,  True, False, False, False],
       [False,  True, False,  True, False,  True],
       [False, False,  True,  True,  True, False],
       [False, False,  True,  True,  True, False],
       [ True, False, False,  True,  True, False]])

In [18]:
arr1[arr1 > 5 ] ##give me all the values where condition is true

array([7, 9, 8, 6, 6, 8, 9, 6, 8, 8, 9, 8, 9])

In [19]:
arr1[arr1 <5]

array([3, 3, 3, 3, 3, 4, 3, 4, 2, 4, 3, 4])

In [21]:
arr1[0][1:4]

array([3, 7, 5])

In [25]:
##Another Method
arr1[0,[1,3]]

array([3, 5])

In [27]:
arr1[2:4,[2,3]]

array([[6, 8],
       [6, 8]])

In [28]:
arr1[2:5,0:2]

array([[5, 4],
       [4, 2],
       [9, 5]])

In [33]:
arr1[[2,3],[0,2]]

array([5, 6])

In [35]:
arr1 = np.random.randint(1,3,(3,3))
arr2 = np.random.randint(1,3,(3,3))
arr1

array([[2, 1, 1],
       [2, 1, 2],
       [1, 1, 1]])

In [36]:
arr2

array([[1, 1, 1],
       [2, 1, 1],
       [1, 1, 1]])

In [37]:
arr1+arr2

array([[3, 2, 2],
       [4, 2, 3],
       [2, 2, 2]])

In [38]:
arr1-arr2

array([[1, 0, 0],
       [0, 0, 1],
       [0, 0, 0]])

In [39]:
arr1*arr2

array([[2, 1, 1],
       [4, 1, 2],
       [1, 1, 1]])

In [42]:
##Matrix multiplication
arr1 @ arr2 ##DOT product

array([[5, 4, 4],
       [6, 5, 5],
       [4, 3, 3]])

In [44]:
arr1/0 ##when we divide an intger with 0 then it gives an error which is zero division error when element of an array divide by 0 it gives infinity (inf) it handles this zero division error

/tmp/ipykernel_98/2180708037.py:1: RuntimeWarning: divide by zero encountered in divide
  arr1/0 ##when we divide an intger with 0 then it gives an error which is zero division error when element of an array divide by 0 it gives infinity (inf) it handles this zero division error


array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

In [49]:
##Broad casting:-Broad casting means you can adding ,subtracting,doinng something with each of the element and every element

In [47]:
arr = np.zeros((3,4),int)

In [50]:
arr + 5

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

In [51]:
arr

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [58]:
a = np.array([1,2,3,4])

In [57]:
# arr + a 
##ValueError: operands could not be broadcast together with shapes (3,4) (5,) 

In [59]:
arr + a

array([[1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4]])

In [60]:
##this all things can we add in row wise manner 
b = np.array([[1,2,3]])

In [63]:
b.T + arr

array([[1, 1, 1, 1],
       [2, 2, 2, 2],
       [3, 3, 3, 3]])

In [66]:
np.sqrt(arr1) ##this function is used to find square root of any array

array([[1.41421356, 1.        , 1.        ],
       [1.41421356, 1.        , 1.41421356],
       [1.        , 1.        , 1.        ]])

In [67]:
np.log10(arr1)

array([[0.30103, 0.     , 0.     ],
       [0.30103, 0.     , 0.30103],
       [0.     , 0.     , 0.     ]])

In [68]:
np.exp(arr1)

array([[7.3890561 , 2.71828183, 2.71828183],
       [7.3890561 , 2.71828183, 7.3890561 ],
       [2.71828183, 2.71828183, 2.71828183]])

In [70]:
np.mean([1,2,3,4])

2.5

In [72]:
np.min([1,2,78,3,54])

1

In [73]:
np.min(arr1)

1

In [86]:
arr1

array([[2, 1, 1],
       [2, 1, 2],
       [1, 1, 1]])

In [ ]:
#expand_dimention >> expends the array by inserting a new axis

In [103]:
np.expand_dims(arr1,axis=1)

array([[[2, 1, 1]],

       [[2, 1, 2]],

       [[1, 1, 1]]])

In [104]:
np.sum(arr1)

12

In [4]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [107]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [111]:
np.sum(arr,axis=0) #Though it seems row wise but it is calculate column wise 

array([12, 15, 18])

In [112]:
arr1.ndim

2

In [118]:
np.expand_dims(arr1,axis=0)

array([[[2, 1, 1],
        [2, 1, 2],
        [1, 1, 1]]])

In [7]:
data = np.array([[1],[2],[3]])

In [8]:
data

array([[1],
       [2],
       [3]])

In [9]:
data.ndim

2

In [10]:
np.squeeze(data)

array([1, 2, 3])

In [12]:
##repeat
np.repeat(data,repeats=3)


array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [13]:
arr = np.array([[1,2],[3,4]])

In [16]:
np.repeat(arr,repeats=2)

array([1, 1, 2, 2, 3, 3, 4, 4])

In [19]:
np.repeat(arr,repeats = 2,axis=1)

array([[1, 1, 2, 2],
       [3, 3, 4, 4]])

In [30]:
np.roll(arr,2)

array([[3, 4],
       [1, 2]])

In [29]:
np.roll(arr,-2)

array([[3, 4],
       [1, 2]])

In [27]:
np.diag(np.array([1,2,3,4]))

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

Binary Operation On array

In [5]:
arr1 = np.random.randint(1,10,(3,4))
arr2 = np.random.randint(1,10,(3,4))

In [6]:
arr1

array([[7, 9, 4, 3],
       [1, 3, 8, 2],
       [7, 3, 6, 3]])

In [7]:
arr2

array([[2, 2, 4, 7],
       [4, 6, 8, 2],
       [3, 3, 3, 4]])

In [8]:
arr1 + arr2

array([[ 9, 11,  8, 10],
       [ 5,  9, 16,  4],
       [10,  6,  9,  7]])

In [9]:
arr1 - arr2

array([[ 5,  7,  0, -4],
       [-3, -3,  0,  0],
       [ 4,  0,  3, -1]])

In [10]:
arr1 * arr2

array([[14, 18, 16, 21],
       [ 4, 18, 64,  4],
       [21,  9, 18, 12]])

In [11]:
arr1 ** arr2

array([[      49,       81,      256,     2187],
       [       1,      729, 16777216,        4],
       [     343,       27,      216,       81]])

In [12]:
arr1 > arr2

array([[ True,  True, False, False],
       [False, False, False, False],
       [ True, False,  True, False]])

In [13]:
~arr1

array([[ -8, -10,  -5,  -4],
       [ -2,  -4,  -9,  -3],
       [ -8,  -4,  -7,  -4]])

In [14]:
# numpy string function
arr = np.array(['pw','skills'])

In [15]:
arr

array(['pw', 'skills'], dtype='<U6')

In [16]:
np.char.upper(arr)

array(['PW', 'SKILLS'], dtype='<U6')

In [17]:
np.char.upper(np.array(['ram']))

array(['RAM'], dtype='<U3')

In [18]:
np.char.capitalize(arr)

array(['Pw', 'Skills'], dtype='<U6')

In [19]:
np.char.title(arr)

array(['Pw', 'Skills'], dtype='<U6')

In [20]:
# mathemmatical functions
np.sin(arr1)

array([[ 0.6569866 ,  0.41211849, -0.7568025 ,  0.14112001],
       [ 0.84147098,  0.14112001,  0.98935825,  0.90929743],
       [ 0.6569866 ,  0.14112001, -0.2794155 ,  0.14112001]])

In [21]:
np.cos(arr1)

array([[ 0.75390225, -0.91113026, -0.65364362, -0.9899925 ],
       [ 0.54030231, -0.9899925 , -0.14550003, -0.41614684],
       [ 0.75390225, -0.9899925 ,  0.96017029, -0.9899925 ]])

In [22]:
np.tan(arr1)

array([[ 0.87144798, -0.45231566,  1.15782128, -0.14254654],
       [ 1.55740772, -0.14254654, -6.79971146, -2.18503986],
       [ 0.87144798, -0.14254654, -0.29100619, -0.14254654]])

In [23]:
np.power(arr1,3)

array([[343, 729,  64,  27],
       [  1,  27, 512,   8],
       [343,  27, 216,  27]])

In [24]:
np.mean(arr1)

4.666666666666667

In [25]:
np.std(arr1)

2.494438257849294

In [26]:
np.max(arr1)

9

In [5]:
arr = np.array([5,6,1,2])

In [7]:
np.sort(arr)

array([1, 2, 5, 6])

In [8]:
np.searchsorted(arr,3)

4

In [9]:
arr1 = np.array([0,1,2,3,0,4])
np.count_nonzero(arr)

4

In [10]:
arr1>0

array([False,  True,  True,  True, False,  True])

In [11]:
np.where(arr1>0)

(array([1, 2, 3, 5]),)

In [12]:
arr1.byteswap()

array([                 0,  72057594037927936, 144115188075855872,
       216172782113783808,                  0, 288230376151711744])

Matrix >> 2d array

In [13]:
import numpy.matlib as nm

In [15]:
nm.zeros(5,dtype=int)

matrix([[0, 0, 0, 0, 0]])

In [16]:
nm.ones((3,4))

matrix([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [17]:
arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([[1,3],[4,5]])

In [20]:
arr1

array([[1, 2],
       [3, 4]])

In [21]:
arr2

array([[1, 3],
       [4, 5]])

In [22]:
arr1 @ arr2

array([[ 9, 13],
       [19, 29]])

In [23]:
a = np.array([[7,5,-3],[2,-5,2],[5,3,-7]])

In [24]:
a

array([[ 7,  5, -3],
       [ 2, -5,  2],
       [ 5,  3, -7]])

In [25]:
b = np.array([16,-8,0])

In [26]:
b

array([16, -8,  0])

In [27]:
np.linalg.solve(a,b)

array([1.11304348, 2.85217391, 2.0173913 ])

In [28]:
##determinant using numpy
np.linalg.det(a)

230.00000000000006

In [29]:
np.linalg.inv(a)

array([[ 0.12608696,  0.11304348, -0.02173913],
       [ 0.10434783, -0.14782609, -0.08695652],
       [ 0.13478261,  0.0173913 , -0.19565217]])